mall:
  aliyun:
    access-key-id: LTAI4Fr5gfYhcVjLMqeRGbuT
    access-secret: IrkcHu6dZyrjPZRushgO76P5392HJ1
    oss:
      bucket: cskaoyan
      end-point: oss-cn-beijing.aliyuncs.com
    sms:
      region-id: cn-hangzhou
      template-code: SMS_173765187
      sign-name: 王道训练营
